### ISSUE TITLE
check slug config examples

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#244] opened 2019-10-10 19:56 UTC
see https://forge.typo3.org/issues/89390

sorry don't have currently time to dig into it, just shouldn't get lost

**Comment by sypets** [comment] 2019-10-11 05:24
there is also an open PR #244

**Comment by cepheiVV** [comment] 2023-05-23 06:53
This issue isn't complete.
The documentation states that the fallback for `nav_title // title` should be:
```
$GLOBALS['TCA']['pages']['columns']['slug']['config']['generatorOptions']['fields'] = ['nav_title', 'title'];
```

while it actually only works with this config:
```
$GLOBALS['TCA']['pages']['columns']['slug']['config']['generatorOptions']['fields'] = [['nav_title', 'title']];
```
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.html#examples

**Comment by linawolf** [comment] 2023-06-23 06:55
@cepheiVV where ibn the dos did you actually find this?

**Comment by cepheiVV** [comment] 2023-06-23 07:18
@linawolf 
I posted the Link to the docs in my message above

<img width="863" alt="Screenshot 2023-06-23 at 14 17 26" src="https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/assets/2963482/515c9f47-e127-438b-806e-faff92ed60fb">

**Comment by linawolf** [comment] 2023-06-23 08:49
Ah you are talking about the changelog entry https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.html#examples itself beeing wrong?

**Comment by sypets** [comment] 2023-11-12 12:56
As mentioned above: **Changelog** changes should be handled as core issues / patches.

The examples in the [changelog](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.html#examples) are wrong (example 2 and 3). I have created a patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81723 (this should be backported to 9.5, but it is my understanding patches will not be backported to versions before 11.5 currently).


The example in the latest "main" of official docs are correct.

* "main": https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Slug/Properties/GeneratorOptions.html#confval-generatorOptions-fields

Even if correct, I do not think example 2 and 3 make that much sense this way, I assume it was intended to use `[['nav_title', 'title']]` instead of `['nav_title', 'title']` so the slugs are not concatenated. (IMHO makes sense to concatenate title and subtitle in this example but not nav_title and title).

Also, it looks like it is easy to get this mixed up - if even the changelog makes this mistake.

If my changelog patch is merged as is, it might be helpful to add some of the ideas to the other docs page as well:

* in the examples left column, if the "simple array" is used, list both variants
* in example 2 and 3, to not concatenate but use fallback
* point out that the "simple array" will lead to concatenation:  ['nav_title', 'title'] =  [['nav_title'], ['title']] and not  [['nav_title', 'title']]

**Comment by sypets** [comment] 2023-11-13 15:12
core patch for changelog was merged, not rerendered yet.

* docs: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.html
* src: https://raw.githubusercontent.com/TYPO3/typo3/main/typo3/sysext/core/Documentation/Changelog/9.5.x/Feature-87085-FallbackOptionsForSlugFields.rst

**Comment by brotkrueml** [comment] 2023-11-13 15:58
See also here: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/724

**Comment by sypets** [comment] 2023-11-14 18:08
Closing: The PR is still open but the examples are not wrong on docs page and examples in changelog have been fixed.

**Closed by sypets** 2023-11-14 18:08 UTC
